### ISSUE TITLE
Error in (function (side, at = NULL, labels = TRUE, tick = TRUE, line = NA, : no locations are finite

### ISSUE THREAD

**Issue by mwodring** [v-julia/recDplot#1]
Hi, I used your example code from the readme on a fasta file and it throws the following error:

```
Error in (function (side, at = NULL, labels = TRUE, tick = TRUE, line = NA, : no locations are finite
Traceback:

1. heatmap.2(as.matrix(PDD_matrix), Rowv = FALSE, Colv = "Rowv", 
 .     dendrogram = "none", col = matlab.like, main = "PDD matrix", 
 .     tracecol = NA)
2. do.call(axis, xargs)
3. (function (side, at = NULL, labels = TRUE, tick = TRUE, line = NA, 
 .     pos = NA, outer = FALSE, font = NA, lty = "solid", lwd = 1, 
 .     lwd.ticks = lwd, col = NULL, col.ticks = NULL, hadj = NA, 
 .     padj = NA, gap.axis = NA, ...) 
 . {
 .     if (is.null(col) && !missing(...) && !is.null(fg <- list(...)$fg)) 
 .         col <- fg
 .     invisible(.External.graphics(C_axis, side, at, as.graphicsAnnot(labels), 
 .         tick, line, pos, outer, font, lty, lwd, lwd.ticks, col, 
 .         col.ticks, hadj, padj, gap.axis, ...))
 . })(at = c(-Inf, NaN), labels = c(-1, 0), side = 1)
```
![pddmatrix](https://github.com/v-julia/recDplot/assets/89640991/6abc634b-f095-4bb1-a00a-086f38e95b69)

The same happens on the Shiny app. 

Unfortunately I can't attach a .fasta here but it's an export from Geneious aligning two Allexiviruses.

**Comment by v-julia** [comment]
Hi. I suggest the problem is that there are only two sequences in your alignment.  Pairwise distance deviation (PDD) matrix is built by calculating the rmse of linear regression for pairwise genetic distances in all pairs of genome regions. As two sequences produce a single pairwise distance, it can't build a linear regression for a single point. Using PDD matrix makes sense only for multiple sequence alignments.

**Comment by mwodring** [comment]
Oh I see! Thanks for getting back to me. Seems I gravely misread the readme as I'd deliberately split it off into individual one-on-one recombination comparisons. I'll look into it more and try with the whole bunch. Should work then.
